[package]
name = "test_helpers"
version = "0.7.0"
edition = "2024"
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
parking_lot = "0.12"
anyhow = "1"
figment = { version = "0.10", default-features = false, features = ["env", "test"] }
